mysite/urls.py
from django.conf.urls import patterns, include, url
from rest_framework import viewsets, routers
from quickapi import views

from django.contrib import admin
admin.autodiscover()

# Routers provide an easy way of automatically determing the URL conf
router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
	url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include(router.urls)),
        
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
)

other/public_html/website/website/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'website.views.home', name='home'),
    # url(r'^website/', include('website.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
		url(r'^test/', 'mypay.views.test', name='test'),
		url(r'^money-ipn/', 'mypay.views.view_ask_money_ipn', name='money-ipn'),
		url(r'^money-subscribe', 'mypay.views.do_subscribe', name='money-subscribe'),
		url(r'^success', 'mypay.views.success', name='success'),
		url(r'^pay-on-site', 'mypay.views.buy_on_my_site', name='pay-on-site'),
		url(r'^pay-now', 'mypay.views.pay_now', name='pay_now'),
		url(r'^purchase-thanks/$', 'mypay.views.purchase_thanks', name='pay_success'),
		url(r'^purchase-cancelled/$', 'mypay.views.purchase_thanks', name='pay_cancel'),

)
#3f2cf0fe3d994fb8dfe6d8f9g2h5
urlpatterns += patterns('',
	(r'^3f2cf0fe3d994fb8dfe6d8f9g2h5', include('paypal.standard.ipn.urls')),
	(r'^paypal/pdt/', include('paypal.standard.pdt.urls')),
)

polls/urls.py
from django.conf.urls import patterns, url, include
from polls import views

urlpatterns=patterns('',

	# ex: /polls/
	url(r'^$', views.index, name='index'),
	# ex: /polls/5/
	url(r'^(?P<poll_id>\d+)/$', views.detail, name='detail'),
	# ex: /polls/5/results/
	url(r'^(?P<poll_id>\d+)/results/$', views.results, name='results'),
	# ex: /polls/5/vote
	url(r'^(?P<poll_id>\d+)/vote/$', views.vote, name='vote'),

)

polls/models.py
from django.db import models
import datetime
from django.utils import timezone

# Create your models here.
class Poll(models.Model):
	def __unicode__(self):
		return self.question
	
	question = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')
	
	def was_published_recently(self):
		return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
	was_published_recently.admin_order_field = 'pub_date'
	was_published_recently.boolean=True
	was_published_recently.short_description='Published Recently?'
	
class Choice(models.Model):
	def __unicode__(self):
		return self.choice_text
		
	poll = models.ForeignKey(Poll)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.views import generic


from polls.models import Poll, Choice

#class IndexView(generic.ListView):
#	template_name='polls/index.html'
#	context_object_name='latest_poll_list'
#	
#	def get_queryset(self):
#		"""Return the last five published polls."""
#		return Poll.objects.order_by('-pub_date')[:5]
#
#class DetailView(generic.DetailView):
#	model = Poll
#	template_name = 'polls/detail.html'
#	
#class ResultsView(generic.DetailView):
#	model = Poll
#	template_name = 'polls/results.html'

# Create your views here.
def index(request):
	latest_poll_list = Poll.objects.order_by('-pub_date')[:5]
	context={'latest_poll_list':latest_poll_list}
	return render(request, 'polls/index.html', context)
	
def detail(request, poll_id):
	poll = get_object_or_404(Poll, pk=poll_id)
	return render(request, 'polls/detail.html', {'poll':poll})

def results(request, poll_id):
	poll = get_object_or_404(Poll, pk=poll_id)
	return render(request, 'polls/results.html', {'poll': poll})
	
def vote(request, poll_id):
	p = get_object_or_404(Poll, pk=poll_id)
	try:
		selected_choice=p.choice_set.get(pk=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		return render(request, 'polls/detail.html', {
		'poll':p,
		'error_message':"You didn't select a choice.",
		})
	else:
		selected_choice.votes+=1
		selected_choice.save()
		
		return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))

polls/templates/polls/base.html
<!DOCTYPE html>
<html lang="en">
<html>
    <head>
        <title>Simple Poll Application</title>
  		<script type="text/javascript" src="{{ STATIC_URL }}js/jquery.js"></script>
    </head>
    <body>
        <div class="container">
            <div class="message"></div>
{% block content %}{% endblock %}
        </div>
    </body>
</html>

polls/templates/polls/detail.html
{% extends "polls/base.html" %}
{% block content %}
<h1>{{ poll.question }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' poll.id %}" method="post">
{% csrf_token %}
{% for choice in poll.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

{% endblock %}

polls/templates/polls/index.html
{% extends "polls/base.html" %}
{% block content %}
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

{% if latest_poll_list %}
<ul>
	{% for poll in latest_poll_list %}
	<li>
		<a href="{% url 'polls:detail' poll.id %}">{{poll.question}}</a>
	</li>
	{% endfor %}
</ul>
{% else %}
<p>
	No polls are available.
</p>
{% endif %}

<div id="jsonResponse"></div>

<script type="text/javascript">
	function make_base_auth(user, password) {
	  var tok = user + ':' + password;
	  var hash = btoa(tok);
	  return "Basic " + hash;
	}

	$.ajax({
		type : "GET",
		url : "http://localhost:8000/users/",
		dataType : 'json',
		async : false,
		username : 'h13640',
		password : 'cayenta',
		data : '',
		crossDomain: true,
		beforeSend: function (xhr){ 
        	xhr.setRequestHeader('Authorization', make_base_auth('h13640', 'cayenta')); 
    	},
		success : function(data) {
			$('#jsonResponse').html(JSON.stringify(data));
		}
	}); 
</script>

{% endblock %}

polls/templates/polls/results.html
{% extends "polls/base.html" %}
{% block content %}
<h1>{{ poll.question }}</h1>

<ul>
{% for choice in poll.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' poll.id %}">Vote again?</a>

{% endblock %}